# Generated by Django 3.0.5 on 2020-06-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200531_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='backend/bug_images/<django.db.models.query_utils.DeferredAttribute object at 0x7f26e2a38358>'),
        ),
    ]
