# Generated by Django 3.0.5 on 2020-05-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200516_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='bug',
            new_name='buggy',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='backend/bug_images/<property object at 0x7f121c3d7458>'),
        ),
    ]
