# Generated by Django 3.0.5 on 2020-05-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200516_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='backend/bug_images/<django.db.models.query_utils.DeferredAttribute object at 0x7fa28b6195c0>'),
        ),
    ]
