# Generated by Django 3.0.5 on 2020-06-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20200603_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to="backend/bug_images/<class 'backend.models.Bug'>"),
        ),
    ]
