# Generated by Django 3.0.5 on 2020-05-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20200517_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='tags',
            field=models.ManyToManyField(blank=True, default=[], to='backend.Tag'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='backend/bug_images/<property object at 0x7feaca2d9458>'),
        ),
    ]
