# Generated by Django 3.0.5 on 2020-05-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20200518_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enrollment_no',
            field=models.CharField(default=1000000000, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='backend/bug_images/<property object at 0x7fa3e9e884a8>'),
        ),
    ]
