# Generated by Django 3.0.5 on 2020-06-03 14:19

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20200603_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=backend.models.Image.upload_to),
        ),
    ]
