# Generated by Django 3.0.5 on 2020-07-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20200703_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='heading',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
